/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import proyecto.Proyecto;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author 1gprog12
 */
public class Principal extends javax.swing.JFrame {
    private BufferedImage img ;
    private static String dni;
    private static int id;

    public Principal() throws IOException {
        initComponents();
        
        img = ImageIO.read(new File("FondoProyecto.png"));
        setLocationRelativeTo(null);
        Image dimg = img.getScaledInstance(img.getWidth(),img.getHeight() , Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        setContentPane(new JLabel(imageIcon));
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,screenSize.width, screenSize.height);
        //setVisible(true);
        //cerrarPestanas();
    }
    /*public void paintComponent(Graphics g)
    {
        g.drawImage(img, 0,0, null);
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        Admin = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        visualizarParte = new javax.swing.JMenuItem();
        validarParte = new javax.swing.JMenuItem();
        modificarParte = new javax.swing.JMenuItem();
        generarInforme = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        visualizarCentro = new javax.swing.JMenuItem();
        crearCentro = new javax.swing.JMenuItem();
        modificarCentro = new javax.swing.JMenuItem();
        eliminarCentro = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        crearTrabajador = new javax.swing.JMenuItem();
        modificarTrabajador = new javax.swing.JMenuItem();
        borrarTrabajador = new javax.swing.JMenuItem();
        perfilAdmin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        crearParte = new javax.swing.JMenuItem();
        modificarAbierto = new javax.swing.JMenuItem();
        perfilLog = new javax.swing.JMenuItem();
        bSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin.setText("Administracion");

        jMenu4.setText("Partes");

        visualizarParte.setText("Visualizar");
        jMenu4.add(visualizarParte);

        validarParte.setText("Validar");
        validarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarParteActionPerformed(evt);
            }
        });
        jMenu4.add(validarParte);

        modificarParte.setText("Modificar");
        modificarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarParteActionPerformed(evt);
            }
        });
        jMenu4.add(modificarParte);

        generarInforme.setText("Generar informe");
        generarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarInformeActionPerformed(evt);
            }
        });
        jMenu4.add(generarInforme);

        Admin.add(jMenu4);

        jMenu5.setText("Centros");

        visualizarCentro.setText("Visualizar");
        visualizarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarCentroActionPerformed(evt);
            }
        });
        jMenu5.add(visualizarCentro);

        crearCentro.setText("Crear");
        crearCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCentroActionPerformed(evt);
            }
        });
        jMenu5.add(crearCentro);

        modificarCentro.setText("Modificar");
        modificarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCentroActionPerformed(evt);
            }
        });
        jMenu5.add(modificarCentro);

        eliminarCentro.setText("Eliminar");
        eliminarCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCentroActionPerformed(evt);
            }
        });
        jMenu5.add(eliminarCentro);

        Admin.add(jMenu5);

        jMenu6.setText("Trabajadores");

        crearTrabajador.setText("Crear");
        crearTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTrabajadorActionPerformed(evt);
            }
        });
        jMenu6.add(crearTrabajador);

        modificarTrabajador.setText("Modificar");
        modificarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTrabajadorActionPerformed(evt);
            }
        });
        jMenu6.add(modificarTrabajador);

        borrarTrabajador.setText("Borrar");
        borrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTrabajadorActionPerformed(evt);
            }
        });
        jMenu6.add(borrarTrabajador);

        Admin.add(jMenu6);

        perfilAdmin.setText("Perfil");
        perfilAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilAdminActionPerformed(evt);
            }
        });
        Admin.add(perfilAdmin);

        jMenuBar1.add(Admin);

        jMenu2.setText("Logistica");

        jMenu7.setText("Partes");

        crearParte.setText("Crear");
        jMenu7.add(crearParte);

        modificarAbierto.setText("Modificar abiertos");
        jMenu7.add(modificarAbierto);

        jMenu2.add(jMenu7);

        perfilLog.setText("Perfil");
        perfilLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilLogActionPerformed(evt);
            }
        });
        jMenu2.add(perfilLog);

        jMenuBar1.add(jMenu2);

        bSalir.setText("Salir");
        bSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                bSalirMenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenuBar1.add(bSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarInformeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generarInformeActionPerformed

    private void validarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarParteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validarParteActionPerformed

    private void modificarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarParteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarParteActionPerformed

    private void visualizarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarCentroActionPerformed
        // TODO add your handling code here:
        id = 0;
        VidCentro v = new VidCentro(this, true);
        v.setVisible(true);
        if(!Proyecto.getCentro(id) && id != 0){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No existe un centro con dicho ID");
        }else if(Proyecto.getCentro(id)){
            Proyecto.mostrarCentro();
        }
    }//GEN-LAST:event_visualizarCentroActionPerformed

    public static void setId(Integer pId){
        id = pId;
    }
    
    private void crearCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCentroActionPerformed
        // TODO add your handling code here:
        Proyecto.crearCentro();
    }//GEN-LAST:event_crearCentroActionPerformed

    private void bSalirMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_bSalirMenuSelected
        // TODO add your handling code here:
        Proyecto.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_bSalirMenuSelected

    private void perfilLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilLogActionPerformed
        Proyecto.mostrarPerfil();
    }//GEN-LAST:event_perfilLogActionPerformed

    private void perfilAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilAdminActionPerformed
        // TODO add your handling code here:
        Proyecto.mostrarPerfil();
    }//GEN-LAST:event_perfilAdminActionPerformed

    private void crearTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTrabajadorActionPerformed
        // TODO add your handling code here:
        Proyecto.crearPerfil();
    }//GEN-LAST:event_crearTrabajadorActionPerformed

    private void modificarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTrabajadorActionPerformed
        // TODO add your handling code here:
        dni = null;
        VentanaDni vd = new VentanaDni(this, true);
        vd.setVisible(true);
        if(!Proyecto.buscarTrabajador(dni) && dni != null){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No existe un empleado con dicho DNI");
        }else if(Proyecto.buscarTrabajador(dni)){
            Proyecto.mostrarTrab();
        }
    }//GEN-LAST:event_modificarTrabajadorActionPerformed

    private void borrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTrabajadorActionPerformed
        // TODO add your handling code here:
        dni = null;
        VentanaDni vd = new VentanaDni(this, true);
        vd.setVisible(true);
        if(!Proyecto.buscarTrabajador(dni) && dni != null){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No existe un empleado con dicho DNI");
        }else if(Proyecto.buscarTrabajador(dni)){
            Proyecto.borrarTrabajador();
        }
    }//GEN-LAST:event_borrarTrabajadorActionPerformed

    private void modificarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCentroActionPerformed
        // TODO add your handling code here:
        id = 0;
        VidCentro v = new VidCentro(this, true);
        v.setVisible(true);
        if(!Proyecto.getCentro(id) && id != 0){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No existe un centro con dicho ID");
        }else if(Proyecto.getCentro(id)){
            Proyecto.modificarC();
        }
    }//GEN-LAST:event_modificarCentroActionPerformed

    private void eliminarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCentroActionPerformed
        // TODO add your handling code here:
        id = 0;
        VidCentro v = new VidCentro(this, true);
        v.setVisible(true);
        if(!Proyecto.getCentro(id) && id != 0){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "No existe un centro con dicho ID");
        }else if(Proyecto.getCentro(id)){
            Proyecto.eliminarC();
        }
    }//GEN-LAST:event_eliminarCentroActionPerformed

    public void tipoTrabajador(Boolean pTipo){
        if(pTipo){
            Admin.setEnabled(false);
        }else{
            jMenu2.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        modelo.GenericaBD.abrirConexion();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static void setDni(String pDni){
        dni = pDni;
    }
//    public void cerrarPestanas()
//    {
//        if(fase2.Fase2.isUnauotra())
//        {
//            jMenu1.setEnabled(false);
//        }else
//        {
//            jMenu2.setEnabled(false);
//        }
//    }
    
    public void cerrarPestanas(boolean prueba)
    {
        if(prueba)
        {
            this.Admin.setEnabled(false);
        }else
        {
            this.jMenu2.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Admin;
    private javax.swing.JMenu bSalir;
    private javax.swing.JMenuItem borrarTrabajador;
    private javax.swing.JMenuItem crearCentro;
    private javax.swing.JMenuItem crearParte;
    private javax.swing.JMenuItem crearTrabajador;
    private javax.swing.JMenuItem eliminarCentro;
    private javax.swing.JMenuItem generarInforme;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem modificarAbierto;
    private javax.swing.JMenuItem modificarCentro;
    private javax.swing.JMenuItem modificarParte;
    private javax.swing.JMenuItem modificarTrabajador;
    private javax.swing.JMenuItem perfilAdmin;
    private javax.swing.JMenuItem perfilLog;
    private javax.swing.JMenuItem validarParte;
    private javax.swing.JMenuItem visualizarCentro;
    private javax.swing.JMenuItem visualizarParte;
    // End of variables declaration//GEN-END:variables
}
